# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Streaming' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Streaming
  pod 'LFLiveKit'
  pod 'Socket.IO-Client-Swift'
  pod 'Alamofire'
  pod 'Google/SignIn'
end
